### ISSUE TITLE
incorrect encoding when exporting to html 

### ISSUE THREAD

**Issue by lili36** [thunderbird/import-export-tools-ng#592] opened 2024-06-30 23:41 UTC
Hello ! it seems to work before, but on y last exports, the encoding in html is wrong...
I always get broken char, if I export in iso8859-1 I get some wrong, if I export in UTF-8 I get other worng (also the initial html mail is supposed to be UTF-8 anyway... but quoted-printable transfer encoding

I get ï»¿  before the start, then Ã© and Ã¨ for example in UTF-8
and "?" display with ISO-8859, because "Ãš" is encoded as Ã&#168; (the è is not passing)

Also, I get 4 different UTF-8 lines in the option panel ?
Is there no" autodetect" option ?
The display of the mail is perfect in Thunderbird.

I can't find no way to have a correct encoded html export...

I use it on Thunderbird 115.12.0 (64 bits)

Thank you !

**Comment by cleidigh** [comment] 2024-07-01 00:10
This should be fixed in v14.1.0 beta.
You can download here :
https://github.com/thunderbird/import-export-tools-ng/issues/575
Christopher

**Comment by cleidigh** [comment] 2024-07-02 17:15
@lili36 
Any chance you tested the beta?
@cleidigh

**Comment by lili36** [comment] 2024-07-02 17:19
Hi ! Thank you for your answer ! not yet, because I was too busy (sick) and also because I don't know how to download and install it via github yet, so I need to check.

**Comment by lili36** [comment] 2024-07-02 17:43
Thanks ! I will do that when I feel better (not yet)

**Comment by cleidigh** [comment] 2024-07-02 17:52
@lili36 
Chicken soup, the do all elixer %-)
@cleidigh

**Comment by lili36** [comment] 2024-07-03 02:04
ahah ^^ is there any risk if I use a beat version (I am afraid of that, don't judge me I am not expert of all this, I just joined github to post the bug)

**Comment by cleidigh** [comment] 2024-07-03 02:42
@lili36 
Totally fair question.
This beta is one cleanup away from release.
I am 99% certain this is a duplicate of resolved
- #581 
@cleidigh

**Comment by lili36** [comment] 2024-07-03 03:35
I was thinking "any risk for my mails ?" (I already have a thunderbird bug telling me I could save 1,7To by compacting my mails, while my disk only has 200Go, so... (also .eml is not supposed to be compacted). I was afraid to add additionnal bugs or loose of mails)

**Comment by lili36** [comment] 2024-07-03 06:18
I tried and just trying to install it makes my thunderbird crash... I get the popup "are you ok to give access to thunderbird/computer and I can't click on cancel or yes, both of them do nothing and I need to reboot thunderbird then.

**Comment by lili36** [comment] 2024-07-03 07:08
also, any option to auto-detect encoding to use to export ?

**Comment by cleidigh** [comment] 2024-07-03 18:00
@lili36 
I'm a bit confused about your comments.
The character set option on the misc tab is only for text and csv files as the label indicates. The html output is always utf-8 with bom. There is no conversion in the html save. If I do a binary comparison with html exports, changing the text export charset, the html outputs are identical.

How are you finding them different?
Also what os and Thunderbird version are you using?
@cleidigh

**Comment by lili36** [comment] 2024-07-03 18:32
Hi,
Yes, changing this option (even if it says it is for text and cvs files) changes the way html is exported.
If I select UTF-8, I get it all wrong because html is in ISO but saved in UTF-8, and half of the characters are wrong (even some sapces)
If I select ISO-8859, I get less wrong characters in html file.
It changes a lot, and I am certain this is this setting, I tested it multiple time. I can't show your a screen right now, I can try to take some next time.

The meta/head is quite long, maybe that is it (if I export in html with thunderbird, I get correct and also shorter and smaller file).

I am on Linux Mint 20.2 Uma using Thunderbird 115.12.0 (64 bits)

Also, I can't install the beta version (could you read my messages above the last one ?)

Thanks !

**Comment by cleidigh** [comment] 2024-07-03 18:45
@lili36 
ok let's back up.
The v14.0.3 did have an error where charset encoding WAS being used for html, that would track your observations. V14.1.0 fixed html to utf-8 bom.

So apologies for not getting that you couldn't install v14.1.0
I have had some people that for whatever reason had issues downloading from github. Can you try a different browser? Also do an uninstall first. In a worst case scenario I will have to send you a dropbox link. Should not have to, hundreds don't have the issue with github.
@cleidigh

**Comment by cleidigh** [comment] 2024-07-03 19:00
Send me an email to my test account : 
test1@kokkini.net
I will send you a dropbox link from my private email.
@cleidigh

**Comment by cleidigh** [comment] 2024-07-05 20:02
@lili36 
I just realized I can post a zip.
Let me know.
[import-export-tools-ng-14.1.0-b5-tb.zip](https://github.com/user-attachments/files/16113395/import-export-tools-ng-14.1.0-b5-tb.zip)

**Comment by lili36** [comment] 2024-07-06 02:52
Hello, I had no issue downloading the file ! I have the file, but the install in Thunderbird fails.
I get the pop-up asking if I accept to give access to whoe thunderbird and computer, and then I am stucked.
Clicking on "no cancel" or "yes" doesn't close it and I need to restart thunderbird.
So this is not a downloading problem, I got it perfectly easily from github.

**Comment by cleidigh** [comment] 2024-07-06 21:07
@lili36 
I am Confused as heck, never had Thunderbird crash/freeze on installing.
So just for the record, what os are you on?

Let's try a couple things.

Then remove v14.0.3
Change to the main tab and close Thunderbird 
Open Thunderbird, make sure no ietng present. Close Thunderbird again and open again.

First let's open the debug console with Control Shift J
Try installing beta again, if it fails, go to console 
If there is anything there, right click, copy all messages and then post here.
Hopefully that will give us some clues.
@cleidigh

**Comment by cleidigh** [comment] 2024-07-08 20:03
@lili36 
Any luck with my suggestions?
@cleidigh

**Comment by lili36** [comment] 2024-07-12 09:53
Hello, I didn't want to try to not loose the parameters, thinking I may as well wait for the release. Else I can create a fresh profile of Thunderbird to test it (but I am currently too busy to do so. I will tell you if I have any news !

**Comment by lili36** [comment] 2024-07-12 11:44
I found my issue here :
https://www.reddit.com/r/Thunderbird/comments/12ykwjm/comment/jht5add/

not solved, unable to install anything (not your extension related...) 
Update works, install no, even with fresh profile. So I won't be able to test until I fix that.

**Comment by lili36** [comment] 2024-07-12 13:06
@cleidigh
Since I edited my message many times, not sure if you see the updated or how your alert works exactly, so new message (sorry)

**Comment by cleidigh** [comment] 2024-07-12 16:50
@lili36 
I did get all your posts.
That is good you found the workaround. It did seem to be a Thunderbird bug.
Can you send me sample emails with the issues?
Use
test1@kokkini.net
I was going to release today, but I will wait a day or so if this has a speedy solution. Let me know your locale also. I will also check the truncation.
@cleidigh

**Comment by lili36** [comment] 2024-07-12 17:51
mail sent.
The truncation is off again in new version, and on on old, this is weird. Not sure if this is linked to the fact that I now use 2 thunderbird profils with 2 versions...I have trouble to reproduce since it vary in time/according to mails.

As I said in my mail, export is failing when there is Mozilla status on top of source code (from mbox to eml) and seems fine if I export directly from IMAP's folder eml.

**Comment by cleidigh** [comment] 2024-07-12 17:57
I think I have the truncation issue found, part of it is the dueling pref for cut to 50. I am removing that from the ui.
What do you mean about the Mozilla-Status? 
it was not clear on the operation?
@cleidigh

**Comment by lili36** [comment] 2024-07-12 18:00
@cleidigh 
details are in my mail.

Step I did :
1) send a mail to myself
2) receive it, and export it directly from IMAP folder -> 1.eml and if I export in html it works fine
3) move this mail to local folder -> it adds some mozilla status and gives 2.eml as a result. Then the html export from this local folder fails. 

1.eml and 2.eml are attached to the mail, but you probably can just reproduce like that.

**Comment by cleidigh** [comment] 2024-07-12 18:04
I am testing truncation, have not gotten to email.
What time will you be online until?

**Comment by lili36** [comment] 2024-07-12 18:06
I am going to bed right now... but I hope to be still alive tomorrow :D

**Comment by cleidigh** [comment] 2024-07-12 18:09
ok
I will see what I can address by tomorrow

**Comment by cleidigh** [comment] 2024-07-13 04:00
I fixed the truncating issue.
I can't reproduce the local folder issue, used same method and your email...
spent hours on encoding, keep getting half results

**Comment by cleidigh** [comment] 2024-07-14 23:03
@lili36 
Ok so subject truncation is fixed.
I also got the mime headers decoding working.
I checked with a number of emails that have mime headers and accented characters in both headers and body.
I got away from UTF8-BOM to straight UTF-8

I did all sorts of copy and export from Local Folders with no problems so may have to look at that later.
I am planning on releasing tomorrow afternoon unless something big comes up. b9 is pre-release.

- #574 

@cleidigh

**Comment by lili36** [comment] 2024-07-15 06:35
Thanks ! Could you reproduce or do you need me to send the corresponding html ?
Issue is also with ISO.
I should test with new b9 ?
@cleidigh

**Comment by lili36** [comment] 2024-07-15 06:36
I get 404 page not found, not in repository, when clicking on the link.

**Comment by lili36** [comment] 2024-07-15 06:59
ok b9 is not here, but I loaded b8, and issue seems fixed. 
Only things is I get different style if I export from IMAP folder or from local folder, because there is more style on direct export (which makes a bigger file, so I guess we could have it all like the one from local folder to
- have smalled saved file
- simple version look nicer to me, because I think he didn't find the class anyway since he has no css file with that on it (<link rel="important stylesheet" href=""> : no external sheet)
There is "<style>div.headerdisplayname {font-weight:bold;}" but seems to be unused in case of Local Folder (because no div, but <b> instead) and unused in the other case too because the class of the div is "moz-header-display-name" and not "headerdisplayname"

<b>De : </b>
instead of
div class="moz-header-display-name" style="display:inline;">From : </div>

But main issue seems resolved even with iso from/to.
Truncation too thanks.

**Comment by cleidigh** [comment] 2024-07-15 16:05
@lili36 
The issue is Thunderbird gives different html for imap vs local folders, it's crazy and even different over time. This is why the mime decoding took so much time. I'm going to hold of on these issues for now as a more complete review of Thunderbird discrepancies is needed.
@cleidigh

**Comment by lili36** [comment] 2024-07-15 16:58
Hi, I guessed so yes... no way to say "lets just put "to" "from" etc in bold and don't care about mozilla style ?
When I save to html using thunderbird build-in tool, I also get lots of mozilla's class in div, but no css sheet to refer too (I guess the sheet is somewhere ?)
They put the header in a table, but this is kind of heavy (especially when you try like me to have the lighter file you can have to optimize space).

anyway this part is minor details compared to what was solved. 

Just to be sure the new version doesn't break anything, I will wait for the official release before I upgrade on my main account.

**Comment by cleidigh** [comment] 2024-07-15 17:08
@lili36 
All those things and more.
My PrintingTools addon does alot with header formatting. Check it out.
@cleidigh

**Comment by lili36** [comment] 2024-07-15 17:10
oh, I didn't know about it... I currently edit manually the mails in text/html to merge one conversation in one unique file, does any add one does that ? I will check your printing tool.

**Comment by cleidigh** [comment] 2024-07-15 17:20
PTNG does not consolidate messages, but that has been requested before.
So many things to do...

**Comment by lili36** [comment] 2024-07-15 17:24
For now, just make sure the new version doesn't break anything big, then I will switch to it (since I deleted the original mail after exporting, I want to wait for the released safe version ahah :D) Waiting for it I just export to .eml, and will pass to html later...
(already better than huge old mboxes)

**Comment by cleidigh** [comment] 2024-07-15 17:42
well that's the idea, not to break things!
b8 is the release minus version change. It's in the Q now

**Closed** 2024-07-17 21:15 UTC
