### ISSUE TITLE
eml imports incomplete

### ISSUE THREAD

**Issue by JSG1948** [thunderbird/import-export-tools-ng#573] opened 2024-05-25 02:06 UTC
I am moving emails from Windows Live Mail 2012 to a folder on my desktop and then to Thunderbird.  I run Windows 11 and the latest versions of Thunderbird and Firefox.  I downloaded the add on this afternoon, so I assume it too is the latest version.

Properties (right click on the folder) on Windows Live Mail says this folder has 19,169 emails.  The folder I copied them to has 19,168.  Unless you have a suggestion, I'll call that close enough.

When I import the files from the desktop folder into Thunderbird, however, the resulting folder has only 18,207 emails.  I have tried this with other folders as well, again with a substantial number of dropped emails.  Since some email dates get screwed up in this process, it's pretty difficult to see what's missing, that is, what got dropped.

With folder containing far fewer emails, I've copied the emails from the original folder to an IMAP folder I created for this purpose, and then when they're downloaded on Thunderbird, I move them from the IMAP folder to a local folder.  When the number of emails to transfer gets above 2-3,000 I start having similar problems to the one just described.

Any suggestions would be VERY welcome.

**Comment by cleidigh** [comment] 2024-05-26 20:51
@JSG1948 
Thanks for the post.
The eml import code has been stable and and quite well tested and used by users.
That said, I am hoping that you were trying to import directly to an imap folder. This is problematic with large imports ( something I need to flag)

Assuming that was the case, do the import to a Local folder. Then if you want folders on imap, copy smaller chunks.
@cleidigh

**Comment by JSG1948** [comment] 2024-05-26 21:24
Thanks for getting back to me.

I was importing to a local folder, not an IMAP folder..  

When I didn’t hear from you, I decided to try doing it the way I had been previously.  I transfer chunks from a local folder to an IMAP folder on Windows Live Mail, and then move them from the same IMAP folder on Thunderbird to the local folder on Thunderbird.  I gave you the numbers using your import add-on.  The result with the IMAP was within 1 email difference.

Once I get all the emails in Thunderbird, I’ll make some decisions about which ones to make IMAP and which not.  Since I use my desktop about 99% of the time, there’s no real hurry to get everything into IMAP, and quite frankly, I’m leery of having my personal data in the cloud anyway.

**Comment by cleidigh** [comment] 2024-05-27 16:12
@JSG1948 
So am I understanding correctly that the imports to LocalFolders were off by one?
I think I remember Live mail having a file per folder for indexing or something. If you didn't filter on emls, file explorer would include that in its file count.
@cleidigh

**Comment by cleidigh** [comment] 2024-05-27 16:59
@JSG1948 
I am surprised by the import errors for IETNG given the users I have had doing large imports. Do you want to try and debug? It's always tricky because you have the files and I don't. I will also do some large import tests with the latest Thunderbird to see it that has affected anything.

@cleidigh

**Comment by JSG1948** [comment] 2024-05-27 17:35
I have zero experience debugging anything, but if you tell me what it entails, I’ll consider it.

**Comment by cleidigh** [comment] 2024-05-27 17:36
@JSG1948 
Quick sanity check.
Did a 1GB mbox import, then exported to eml(19492 msgs)
Then imported all in folder, result 19492 imported

So it doesn't look like Thunderbird broke anything. Maybe we have to look at content issues. What type of mail account do these messages come from. I have had issues with Exchange accounts and having to deal with some headers
@cleidigh

**Comment by JSG1948** [comment] 2024-05-27 17:45
I don’t understand the question: what type of mail account?  

The files are stored by Windows Live Mail 2012.  For many years, it was a POP account; then at some point I converted it to IMAP.  Doe that answer your question?

**Comment by cleidigh** [comment] 2024-05-27 18:08
I'm asking who the host type of account was, a Microsoft account?
Just knowing the issues I have had...

The debugging will require some back and forth trying to identify the emails that don't import, then analyze those.
 
We seem to have time overlap which helps, where are you located?
@cleidigh

**Comment by JSG1948** [comment] 2024-05-27 19:43
To answer your second question first, I ‘m in southern Vermont.

The server was Coppernet, a firm pretty much no one has ever heard of.  I’ve been using them since dialup days, which given that this is a rural area, lasted longer here than elsewhere.  Coppernet appears to be dying  (https://copper.net/faq/) and that’s a major part of why I’m trying to get everything moved.  Windows Live Mail 2012 (WLM)  is obviously already dead.

My intention is to get everything on Thunderbird, including my address book and then switch to Proton Mail where I’ve opened an account.  Once that’s up and running, I will change to a new address (Proton.me, but maybe using an alias (I’ll explore that) and retain the old address only because I’ve had it so long everyone is used to it (including my online book customers – I’m a used and rare  book seller).

I’m now on Windows 11, which keeps trying to get me to set up on Exchange, but I’ve avoided doing that.  I’d just as soon avoid all the big guys: Microsoft, Google, etc.

I just tried my old IMAP method on a folder which WLM says has 61,324 emails.  I ended up with 88,139 after various crashes and other problems.  I’m going to try doing this again (I’m doing it in chunks and it’s very time consuming).  Is there an easy way to filter out emails which are completely identical?  Same sender, recipient, subject line, and body in Thunderbird?

**Comment by cleidigh** [comment] 2024-05-27 19:57
@JSG1948 
Real books that's excellent! I am just south of you in Providence, Ri. I'm not online until noon as I am disabled.
The first couple of things to do are this:
- Find your smallest folder that does not completely import
- Check to see if it is consistent in how many emails are not imported
- If the number is consistent, then we hopefully have a formal issue we can identify 
- We then break the files down to id the problem ones

I am slow today and have visitors. If you want try to start the above 
@cleidigh

**Comment by cleidigh** [comment] 2024-05-27 20:01
oh yes there is an addon
https://addons.thunderbird.net/en-US/thunderbird/addon/removedupes/?src=hp-dl-mostpopular

you are making me wonder about numbers from LV

**Comment by JSG1948** [comment] 2024-05-28 00:40
I will look at this later.  

What’s an LV?

**Comment by cleidigh** [comment] 2024-05-28 01:52
sorry, meant LM, Live Mail
I mistyped on my eye gaze.

**Comment by JSG1948** [comment] 2024-05-28 02:10
Thanks for the clarification.

**Comment by JSG1948** [comment] 2024-05-29 03:04
I’ve had a very frustrating day, after a pretty darned good one yesterday.  

Yesterday, I moved 61324 emails in one of my larger folders (in chunks).  It took all day and various repeats, but eventually I ended up – using the IMAP method – with 61369, which is close enough.

Using the import tool, I ended up with 88.139, but I suspect that’s because some chunks got imported twice..  I tried to download the duplicates add-on, but Firefox  wouldn’t let me/  I just realized that I should have been trying in Thunderbird, not Firefox, and it downloaded successfully.  I’ll try it later to see if I can get that number down to similar or even better than the IMAP method.  

Meanwhile, I spent the day trying to do IMAP downloads, with smaller and smaller chunks, but something is fucked up.  Still.

I copy a year’s worth of emails from a local folder in WLM to an IMAP folder.  Unfortunately, I don’t see any way to see the number of the emails being copies OUT OF the local folder.  

I won’t bore you with all the screwups that I’ve encountered all day, but will try to be especially careful and recount what I’m encountering now.  I’ve checked and re-checked my IMAP folder (“transfer”), the deleted folder and the trash folder in WLM.  All say there are 0 files.  I’ve closed and re-opened Thunderbird.  Same thing.  0 everywhere including the local folder into which I want to move the files from the IMAP folder “transfer.”

Now, I’m going to copy the same emails that went into my desktop folder from the local folder where they’re stored in WLM to “transfer.”  Transfer in WLM says 198 messages.  Transfer in Thunderbird says 0.  The subscribe menu under File shows NO folders, even when I hit refresh.  So I’m going to close and re-open Thunderbird.

Thunderbird shows the folders under the email address, but not when I go to Files, subscribe, refresh.  It shows nothing.  I’m going to give up now,.  I’ve put enough time into it today.

So I finally got around to trying the import again.  There are 198 emails in the directory on my desktop and 193 in the folder on my computer into which I imported them.  So it appears to have dropped 5.

Yours in considerable frustration.

**Comment by cleidigh** [comment] 2024-05-29 17:57
@JSG1948 
I totally understand your frustration. I have been through many similar scenarios helping with transfers like this. There are just so many variables.

I am not sure what you would like to do at this point, but let me know.
@cleidigh

**Comment by JSG1948** [comment] 2024-05-29 18:51
Thanks Christopher.

I just sent this message to Thunderbird so we’ll see what comes of it: https://support.mozilla.org/en-US/questions/1448597

If you have any suggestions about showing 5 fewer emails in the imported file than in the desktop folders, I’d appreciate it.  Obviously, I could try to find them one by one, but do you have a less tedious method for doing so?  I just did another import from a desktop folder containing 71 and got 70.  MY IMAP transfer folder also shows 70.  I’ll try another batch.

**Comment by cleidigh** [comment] 2024-05-29 18:59
@JSG1948 
ok a folder with 71 is a good one to work with 
Let me understand clearly. What were you importing with? 
The source folder is a desktop folder.
If you do a windows search on that for *.eml what do the search results show?

Christopher

**Comment by JSG1948** [comment] 2024-05-29 19:18
I marked off the 70 emails in an existing local folder, and then dragged them into the new folder on my desktop.

Then, in TB, I used your tool to import them into a local folder under TB.

When I mark them, I don’t see a count.  In the desktop folder, it says there are 71.  In the TB local folder: 70.

Interestingly, as a separate operation, I also right clicked on the same files in the WLM local folder and copied them to my transfer folder which says 70.

Where do you want me to t do the Windows search?

****** 
Carrying on, I marked another 266 (according to desktop folder) and got 262 in TB using your tool.

**Comment by cleidigh** [comment] 2024-05-29 19:27
ok
so far the search
go to the desktop folder and do a search with file explorer for *.eml and see what the count is
im slow and have issues with eye gaze and eyes, bear with me

**Comment by JSG1948** [comment] 2024-05-29 19:45
That may have helped some.  There is one email which doesn’t show up, and which shows up differently in the list.  But when I click on it to open it, it says that it’s an .eml file.  So that must be the one not importing. Under “type” the others show uo as Thunderbird document (and with the date change to today) in the folder, whereas this one shows as eml.

When I went to 2007, I just arranged the emails by type.  Same thing.  Most show up as TB docs; 4 show up as .eml and don’t transfer.

**Comment by cleidigh** [comment] 2024-05-29 19:53
now it's really confusing.
When you look at these folders can you set file explorer to show the full filename with extensions.
There sounds like a name issue according to your observation

**Comment by JSG1948** [comment] 2024-05-29 19:58
The ones showing up as being .eml for a type have a name, then underscore, then period then eml: NAME_.eml; the others show up without the underscore: NAME.eml

**Comment by cleidigh** [comment] 2024-05-29 20:08
ok
the ones with the underscore don't have the Thunderbird icon?
In the folder with 71 files is there just one with an underscore and 70 without?
Can you import the single underscore file?

**Comment by JSG1948** [comment] 2024-05-29 20:09
Just did another batch: 9545 in folder 9469 imported.  Same thing.  76 .eml with the underscore.  So how do we get those into the same format as everything else?

I’m heading out for a walk, then probably lunch, So there will be a delay in my responding.

**Comment by JSG1948** [comment] 2024-05-29 20:18
The answer to the first 2 questions is yes.   To the third, how?

I guess I could try to move the offending ones (with the underscore) to a new folder, and try to import.

Looking at one of them in the original local folder, I don’t see anything which distinguishes it from all the others.  Ideas?

Now heading out.

**Comment by cleidigh** [comment] 2024-05-29 20:41
So in the folder with one 71 files including one with an underscore, ImportExportTools imports 70 messages. It should be easy to check if the one underscore file is the one missing.

Open it with notepad and locate the Subject: line
then check for that in your imported folder.
If that is not imported could you send it to my private account?

To import individual eml messages, right click on a local folder and import eml messages /individual eml messages

**Comment by JSG1948** [comment] 2024-05-29 21:07
Back from walk.

I tried copying it from the folder with everything to a new folder with just it.  When I looked for it with your tool in either folder, it doesn’t show, but it DOES show when I just look in the file.  I think I said that these are _.eml, but they are ._eml, which I think is the problem.

So, in the new folder (with just the one email, I removed the underscore, which made the Thunderbird icon appear and then imported it successfully.

Is there a find and replace tool that I could use to do this instead of removing the underscores manually?

What is your personal account’s address?  I can send you a sample of the offending emails.

**Comment by cleidigh** [comment] 2024-05-29 21:27
progress!
so to recap
the files with an underscore are not recognized by windows as Thunderbird /eml files nor ImportExportTools 

note an underscore is perfectly valid, see the top eml i renamed with underscore

![image](https://github.com/thunderbird/import-export-tools-ng/assets/25272315/90841f6c-d0a1-4c24-9f22-8977d2458ecf)

I think there is something hidden that makes it a non.eml file
I'm trying to think how to analyze
does it look like an eml when opened in notepad?

**Comment by cleidigh** [comment] 2024-05-29 22:01
https://www.experts-exchange.com/questions/27099019/When-I-Drag-Drop-EML-Files-To-My-Desktop-They-Now-Become-EML-Files-WHY-I-Want-It-Back-To-Normal.html

**Comment by JSG1948** [comment] 2024-05-29 22:26
I’m going to take a nap.  When I open it with an email app, it looks like an email.  If I open it or edit it with notepad, they all (with or without the issue) appear to look the same.  But of course, I don’t know what I’m looking for, and there’s a lot there.

I’ll look further at the link you sent when I get up.

You didn’t send me an email address that’s different from the one I’ve been using.

**Comment by cleidigh** [comment] 2024-05-29 22:51
so far i dont think you need to send anything 
the problem is getting a clean eml export 
drag and drop is not seeming to be the way
i found many tool for this, some not too expensive 
if you get a clean export they will import 
have to transfer to bed

**Comment by cleidigh** [comment] 2024-05-29 23:09
https://weirdkid.com/emailchemy/

**Comment by JSG1948** [comment] 2024-05-30 02:58
I have very good news.

I have successfully moved another large folder, this time using your tool.

The WLM folder contained 56974 emails; somehow the TB contains 57096.  Intriguingly, all of the smaller batches lined up perfectly.  It is possible that the WLM count is different from what the folders (and now TB) counted.  That, I can’t say.  But since there are more than before, it’s unlikely that I’ve lost any, and some duplicates aren’t going to bother anyone.  I have plenty of disk space.

Here’s what I did.

I dragged the files from the WLM file to a series of desktop folders, which I organized by dates, usually a year or 2’s worth at a time.  That way, the batches didn’t get too out of hand.

As I reported earlier, the folder files contained both TB emails recognized as such (*.eml) and folders with the extension (*._eml) which your tool did not recognize.  I then moved the latter into a new folder, so that ALL of the emails in the folder had the non-TB extension. (I don’t think I need to actually move them.  I’ll experiment with that tomorrow).

The I went to the command prompt, and changed to the directory holding the *._eml files and used the command ren *._eml *.eml.  Doing so immediately caused them to recognized as TB files, and then your tool successfully imported them,  As I say, I reviewed the numbers batch by batch and they matched perfectly.

I’m pretty sure that instead of creating all these new directories for the “bad” extensions, I can just use the ren command in the batch folder BEFORE importing, which will simplify matters a great deal.

I have absolutely no idea why the bad extensions came into being in the first place: that is, I can’t explain why some emails had the proper .eml extension while a minority got the added _ which fucked things up.  A cursory look in notepad didn’t show any differences.

Obviously, if others are encountering the same issue, it would be even easier to have the tool directly import files with the *_.eml extension rather than having to convert them, but that’s a relatively small matter.

I’m still trying to figure out why TB decided today to ditch my IMAP folders.   That will be for another day.

Thank you so much for all your help.  It was invaluable.  I can’t tell you how pleased I am to have gotten to this result.  Hopefully, there will be no setbacks tomorrow!

**Comment by cleidigh** [comment] 2024-05-30 16:34
@JSG1948 
If I add the._eml extension to the file filter in a beta today, would you use it to complete your imports?
Christopher

**Comment by JSG1948** [comment] 2024-05-30 16:40
Sure, good timing.  Let me know when it’s ready.

**Comment by cleidigh** [comment] 2024-05-30 16:49
Probably an hour or two

**Comment by JSG1948** [comment] 2024-05-30 16:53
ok, just let me know.,

**Comment by cleidigh** [comment] 2024-05-30 18:51
@JSG1948 
This is my beta 14 for v14.0.3
I have added support for importing  ._ Eml
files.
If you import individual files, the filter will show both types. Selecting a folder will import all of both.

Download the file and install from the gear icon in addons tab.
Reboot Thunderbird after installing.

https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b14-tb.xpi

Christopher

**Comment by JSG1948** [comment] 2024-05-30 19:24
I tried it on one file and it came up short, but I’m guessing I did something wrong.

I clicked on the link and get a page which doesn’t include anything that I can see for downloading.  When I used the Thunderbird gear to install it, I/m guessing that it installed the previous version (the one I already had).  I didn’t see anything anywhere about both kinds of file.  I imported one of the new folders which, according to properties has 11730 files.  11650 came through, and there appear to be 79 ._eml files in the folder (still). In other words, it did NOT import the *._eml files.

for now, I’ll leave things as they are until you get back and tell me what to do.

**Comment by cleidigh** [comment] 2024-05-30 19:32
@JSG1948 
On the link page there is a download link, a a downward arrow into a tray.
Then use Install from file under gear icon. It will show help for b14 then restart Thunderbird.
Then try import individual and you should see _eml files

**Comment by JSG1948** [comment] 2024-05-30 20:54
The download link doesn’t work.  Clicking it appears to do nothing.  Usually it would give me an option to save it as a file.

**Comment by cleidigh** [comment] 2024-05-30 21:26
should go to your download folder

**Comment by JSG1948** [comment] 2024-05-30 22:19
Nope.  I’ve set up Windows (or at least, I think I have) so that it asks me where to save files rather than doing so automatically.  I generally put them on the desktop.  I checked documents, downloads and desktop just to be sure.  Nada.

**Comment by cleidigh** [comment] 2024-05-30 22:23
when you hover over icon it says download?
Maybe try another browser?
Never heard of this, it's used all the time.

**Comment by JSG1948** [comment] 2024-05-30 23:52
It says download raw data.  Did the same thing in Edge and Chrome as Firefox.  Show that message, but when clicked, nothing.  Re-checked dowkads, documents, desktop.

I’ve downloaded many files this way.

**Comment by cleidigh** [comment] 2024-05-31 00:22
That is crazy infuriating!
I don't know what to say
what is another way to get you the file?

**Comment by JSG1948** [comment] 2024-05-31 00:30
Sorry.

I can think of 2 ways.  

1) Update the TB adds on with a 2nd add on that says beta.  That way, you keep the original and provide me and others access.
2) Send me the file directly in a format that I can access in the TB add on  gear menu.

**Comment by cleidigh** [comment] 2024-05-31 00:50
no it Can't go on site
I will find one of the  xfer sites.
I also might point you to another link
this is so crazy, millions of users do this 
do you have any settings that could block this?

**Comment by JSG1948** [comment] 2024-05-31 00:54
I don’t think so,  Like I said, I’ve downloaded many files, including using the arrow tool

**Comment by cleidigh** [comment] 2024-05-31 01:17
try downloading the xpi asset here
don't install, I have to create a new one, just to check 
https://github.com/thunderbird/import-export-tools-ng/releases/tag/v14.0.2

**Comment by JSG1948** [comment] 2024-05-31 01:24
There’s no download too there at all.  Of if there is, I’m missing it.

**Comment by cleidigh** [comment] 2024-05-31 01:39
click the first blue xpi link

**Comment by JSG1948** [comment] 2024-05-31 01:52
Firefox won’t let it download: “github.com.  Firefox has prevented this site from installing an unverified add-on.” It then links to  :Add-ons that can change your browser's settings without your consent or steal your information have become increasingly common. Some add-ons can add unwanted toolbars or buttons, change your search settings or inject ads into your computer. Firefox does now verify that the add-ons you install have been signed by Mozilla, digitally. This article explains the add-on signing feature and how it works. :https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox?as=u

**Comment by JSG1948** [comment] 2024-05-31 16:24
Are you still working on this or should I go ahead and get my emails moved using the last method I described night before last?  I’ll wait, if it will help you test, but I’d like to get this done sooner rather than a lot later.

**Comment by cleidigh** [comment] 2024-05-31 16:29
Yes, I just posted to the wrong thread...Lol

Allright, we will try a dropbox link.
If you can send an email to my test account :
[test1@kokkini.net](mailto:test1@kokkini.net)
I will send a db link
Christopher

**Comment by cleidigh** [comment] 2024-06-02 18:55
@JSG1948 
I am going to close this.
Good working with you.
@cleidigh

**Closed by cleidigh** 2024-06-02 18:55 UTC

**Comment by JSG1948** [comment] 2024-06-02 19:02
Thanks.  

Closing it makes sense.
