### ISSUE TITLE
Some Folder and Subfolder are not filled after import

### ISSUE THREAD

**Issue by HBsTB** [thunderbird/import-export-tools-ng#497] opened 2023-11-13 15:28 UTC
Hi, I am the first time here, because I am using "ImportExport-Tool NG" the first time.
Its Version 14.0.0 which i downloaded today.
My Thunderbird is on V 115.4.2 (32 bit).

I want to convert the thunderbirds folderstructure to mbox-format because of the intension to convert to pst-Format for using the same structure in outlook.

To test it, I marked a choosen folder and uses the right mouse button to open the ImportExport-menue.
There I choose "Folderexport(mbox)/structured with Subfolder".
The result is stored in a folder ending on ".sbd" and in a file ending on ".mbox".
To controll this export-data I create a new folder in thunderbird, choose with right mousebutton "import mbox-data/all mbox-data of the folder(SBD-Structure)" and started the import.
The comparation with Original-data shows some lost Mails. They are missing in singlefolders as well as in Subfolders but not basicly. Most are imported to Singlefolders or Subfolders correct.

The missing mails I often misses them in Firstfolders.
The First folder in the exported structure ,where are mails missed, is a singlefolder.
In the first multiple-folder is it the first subfolder with missed mails.

Have i to configure the options especially ?

thanks for tips and solutions

Hans

**Comment by cleidigh** [comment] 2023-11-13 18:51
@HBsTB 
Sorry for the confusion. Let's break this down and go step by step. First thing, I literally just released v14.0.1 today, probably just after you download v14.0.0. You should update to that because it have an important patch for mbox import that can catch an edge condition causing message import problems.

Now two things you said confused me, the first is your mention of pst. IETNG does not do anything with pst so if you think this is relevant maybe you can give me more details. For the export and import of mbox we can start just focusing on what IETNG does.

The second thing that I did not understand is what you saw after the export. Each folder exported for a structured export should be the folder name without any extension, I don't add a . mbox extension for structured exports. If you could capture a screenshot of the top level export from file explorer that would help me see.

I understood you see some messages missing after import. This is something I hope the v14.0.1 fixes. What was not clear to me was if the imported folder structure was complete and accurate.

Let me know if v14.0.1 resolves the import issue and I can also look at your screenshot.
@cleidigh

**Comment by cleidigh** [comment] 2023-11-14 20:33
Hans
I think the most important thing is to first identity folders that do not export and import correctly and hopefully we can troubleshoot those.
The best place to start is to identify the smallest folder that has problems and we will try to see what is going on. Use the individual mbox file export and then the individual import.
Once we have specific results for that we can try to isolate the missing messages and analyze.

One note: Any structured export WILL NOT HAVE MBOX EXTENSION, individual exports will follow the mbox extension option.
Christopher

**Comment by HBsTB** [comment] 2023-11-15 14:26
Hi Christopher.
Using the individual export means this ?
![TB_IETNG1](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/a7cbfe5b-c9bb-4bda-90e7-0021f789d845)
I want to export this folderstructure
![TB_IETNG2](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/ed9169b5-5ec1-4a44-bfc7-4a47f366027a)

With this selection I get 1 mbox-File.
![TB_IETNG5](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/2669fba2-26b8-4774-82f8-fee173c9ee21)

Is the import correct with this choose ?
![TB_IETNG4](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/3080a42a-4fdb-435c-ad56-f5ce19f766de)

With it I get only the first-/mainfolder "Makler_Engelen", no Structure and only 6 from 17 Mails.
![TB_IETNG3](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/51b6025f-b34e-4e20-b40f-d0c6092a8e56)

Where ist the structure ?
Without it we can't go on as you have porposed, i think.

Thanks to your seemly never ending patience.

regards
Hans

**Comment by cleidigh** [comment] 2023-11-15 17:36
Hans
Yes there is always some patience involved with software ;-)
However, the main thing is I want my users to be able to accomplish there goals with as much ease and success as possible. It's also my pride in work, i want the tool to be accurate and reliable as possible. What you are trying to do is not special and should work. The export and import mbox code was totally rewritten for v115 and I have to make sure its reliable. So let me summarize where we are:

- From your screenshots, you did exactly what I wanted 
- You did a single folder export of Makler_Engelen 
- This results in a single mbox file 
- There is no structure because mbox files contain only messages from one folder 
- Your last screenshot is the result of importing the Makler_Engele.mbox file from your export, yes?
- Now before exporting you had 17 messages in Makler_Engele, yes?
- After importing you see six, However, there are are two collapsed threads 
- So depending upon the thread lengths, there will be more than 6 messages 
- Now I don't know if that gets you to 17
- If not then we have an import issue 
- Let me know if I have stated anything incorrectly 

So the folder Makler_Engelen is perfect because it's very small and easy to analyze and test
The idea is that if we figure out the issues with this folder hopefully it solves the others. This leads me to the next best step:

Would you be comfortable sending me privately (not here) the Makler_Engele.mbox file you exported? I have had many users entrust me in this way because frankly it's very difficult without the actual data. I would of course destroy as soon as we fix the issue.

If this is not possible then we will have to figure out another way. After this we would look at a folder you said imported with nothing.

If you feel comfortable sending me the Makler_Engelen file, send to my test account : 
test1@kokkini.net
I will confirm with my Gmail account.
Chuse
Christopher

**Comment by HBsTB** [comment] 2023-11-16 15:15
Hi, Christopher.
I have a problem with zip-File-size. Sending it may be force the risk of a not complete zip-file.
Mbox-Originalsize is 43MB, as zip I only could reduce to 28MB.
My Mail-account is not permited sending such big files.
I can open the mbox-file with the usual WIN-Edit. It seems the correct character set. I am able to read all Informations.
The file has 585735 rows.
Is it sencefull to create 5 txt-Files with a circum of 118000 rows in each file ?
What other chance we have ?

greetings
Hans

**Comment by cleidigh** [comment] 2023-11-16 17:36
Good afternoon Hans
Yes always a problem with large files. Do you use any of the cloud based file transfer providers?
I think Thunderbird has several they support. Is that a possibility?
Otherwise is there a smaller folder that you also have a problem with?
The other thing I will check is if github has any private post methods.
Christopher

**Comment by cleidigh** [comment] 2023-11-16 18:42
Hans
Github does not have anything.
Here is one free transfer service
https://www.transfernow.net/en

While splitting the files should work, i am paranoid that we will glitch it somehow.
Last resort would be to copy the folder, remove a few large messages, re-expport/import, verify you still have the problem and send that.
Christopher 

Christopher

**Comment by HBsTB** [comment] 2023-11-16 19:19
Christopher,
files are on their way.
greet you

**Comment by cleidigh** [comment] 2023-11-16 19:48
Hans
The comparison is perfect, that will help.
Christopher

**Comment by cleidigh** [comment] 2023-11-16 20:03
Hans
Already found an issue, thanks so much for sending!
Have my call, more later.
Christopher

**Comment by cleidigh** [comment] 2023-11-16 20:33
Hans
Are you still online, our meeting seems delayed.
I wanted to see if you can send me the internal mbox file.
- right click on the folder we are analyzing 
- choose open the folder directory
- now look for the folder name with no extension 
- if you can send me that file I can compare

It looks like Thunderbird is messing us up
Christopher

**Comment by HBsTB** [comment] 2023-11-16 21:04
Christopher
if choose with right click on the folder "Makler_Engelen" i get this picture...
![TB_IETNG7](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/eb921351-b86c-410d-a61d-d7120c1a2950)

in it i can't find ""open folder directory"

If i choose like this...
![TB_IETNG8](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/07e6d4a8-d9e8-4c60-9a8e-e2d5642b2d02)

... I find the menue item but nothing happens.

is a screenshot possible ?

Hans

**Comment by cleidigh** [comment] 2023-11-16 21:28
That should open the file explorer 
Do you have multiple Thunderbird windows open?
You are on Windows?
The other way will be more awkward, but I can walk you through it so we can avoid debug on this.
Next message I will tell you what I found
C

**Comment by cleidigh** [comment] 2023-11-16 21:38
So here is the first few lines of the first missing message with the subject Am-info.
I have sanitized names for privacy.
```

From xxx@web.de Sat, 08 Jul 2017 13:21:12
X-Mozilla-Status: 0009
X-Mozilla-Status2: 00800000
X-Mozilla-Keys:                                                                                 
To: abc <mmm@sec-ac.de>
From: "ghj.de" <xxx@web.de>
Subject: AM-Info
```

See the X-Mozilla-Status: 0009
That's Thunderbird flags for READ + EXPUNGED 
This is how Thunderbird marks messages that have been deleted, but not compacted yet.
It makes no sense, but when we import them they get deleted. There are ten of these so instead of 24 you get 10!
Christopher

**Comment by HBsTB** [comment] 2023-11-16 22:14
Hey, wow.
This last message comes unexplainable to me.
The subject "AM-Info" is an old Mail. 
My experience after deleting mails is that I can't see them anymore.
I have so often restart Thunderbird, have so often do backups and this subject has not been compressed.
How does this works ?

But...what do you mean with "That should open the file explorer" ?
What is "that" ?

My standrad-using of Thunderbird is one tab with 3 Mail-Accounts, one tab for Calendar and one for tasks.

Yes I am using windows 10.

What will be next steps ?
What do I have to do ?

greets
Hans

**Comment by cleidigh** [comment] 2023-11-16 22:33
Sorry I threw a lot out there.
The menu option 
Open folder directory should open the windows file explorer where you see your windows folders and files. I don't know why that is not working.

I will try to give you a way to get there later.

The whole problem is that for some reason Thunderbird has marked these messages incorrectly as deleted. Obviously you can see them so they are there.
I export these correctly, however, when we import them  Thunderbird deletes them.
This is a Thunderbird issue I must investigate.

So what I am going to do is the following. I will make a beta version of IETNG that resets the flags on export and then the import will be ok.
Christopher

**Comment by cleidigh** [comment] 2023-11-17 18:32
Hans
Good afternoon.
I think I have a beta that should solve the export with flags reset. Then on import Thunderbird will see all messages as valid. I could not completely reproduce your scenario because Thunderbird kills the other messages no matter what I do. I can test the reset so I believe this should work.

You will load this from the addon tab using Install Add-on from file then choose the xpi you download. Note the download has github quirk so read download note.

If you get a corrupted message on install make sure you follow the download method here:
https://github.com/cleidigh/printing-tools-ng/issues/154

b2 xpi
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.2/xpi/beta/import-export-tools-ng-14.0.2-b2-tb.xpi

Try the individual export import and if everything goes right you should get all 24 messages. Then try your full structure and see what we get.
Christopher

**Comment by HBsTB** [comment] 2023-11-18 13:56
Christopher,
I think I have found the internal mbox-file.
In the folder "C:\Users\User\AppData\Roaming\Thunderbird\Profiles\gf3z6uec.default\Mail\HBs.sbd..." I find a file named "Makler_Engelen" without extension in size of 43MB. It's however from 16.12.2022.
I send it.
Hans

**Comment by HBsTB** [comment] 2023-11-18 14:11
Hey Christopher.
Here my Transfer-Report.
The Download of your beta seems easy.
This is the result in my AddOn-Tab...
![TB_IETNG1](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/e030cd3e-d134-4f13-85fe-df61d38953fe)
With it I started an export with...
![TB_IETNG2](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/c542ec33-ed20-49ee-814f-f93228825c00)
and have imported with...
![TB_IETNG3](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/83df2ccd-2be3-44a5-af2a-9085d6de3441)

so, the same procedure as before beta and...but sorry, with the same result as before beta...
![TB_IETNG4](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/4edb5c90-5790-486c-8360-404c2d845b66)

But this shouldn't still be. What is wrong ?

Hans

**Comment by cleidigh** [comment] 2023-11-18 18:57
Hans
Did you restart Thunderbird after installing the beta? The new export code won't be used until the restart. Then export and import. If still not correct, send me the exported mbox. If this isn't right I will have to send debug code.

Sorry for the process, but we will get it because I can see the issue, just have to get those flags reset.
Christopher

**Comment by HBsTB** [comment] 2023-11-18 19:42
Christopher, congratulations, it works perfect.
I oncemore forgot this basicly simple action.
Now i'll start the original great task.
The export is done. Aktually the import is running.
After that i try to compare the data.

I'll report.
Thanks so long

Hans

**Comment by cleidigh** [comment] 2023-11-18 20:00
Hans
I am so glad that is what it wa, HOWEVER, I just found one error in my flag reset logic. I have to detect hexadecimal characters. If you check your top folder it will have 22 messages, not 24 because the reset missed 2.
So don't do your full Export yet. I will send you my fix shortly.

Here is my full 24 message import 

<img width="960" alt="image" src="https://github.com/thunderbird/import-export-tools-ng/assets/25272315/5a2d695d-daa9-45b0-b829-df1c9ca8a94d">


Christopher

**Comment by cleidigh** [comment] 2023-11-18 20:39
Hans
Ok with b3 you should get all 24 messages in your top folder. If so, go ahead and do your full Export.
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.2/xpi/beta/import-export-tools-ng-14.0.2-b3-tb.xpi

Christopher

**Comment by HBsTB** [comment] 2023-11-18 21:10
Christopher, thanks.
My short comparation has shown some missing mails, so that your new version may be correcting this.
I'll repeat the big export and import, what will take much time.

you will get Info

Hans

**Comment by HBsTB** [comment] 2023-11-19 09:46
Hi, Christopher.
While comparing the great import i wish to be able seeing the mail- count to each folder, which has been exported.
That might do this work easier.
After import i see the counts at the imported messages but i guess because of the fact, that all imported messages are declared "unread" by TB and only in this case are counts shown by TB .
The counting is not usual for "read" messages.

Do you have a tip to set the counts also at "read" messages ?

In Web I read about a menue-item in an older version of TB where this feature is switchable respectivilly chooseable.
In actual TB-Version i can't find this item.

Tanks for help
Hans

**Comment by cleidigh** [comment] 2023-11-19 17:56
Hi Hans
Can you give me an overall status of what we have accomplished?
- I the full folder structure exporting and importing correctly?
- Do the TOTAL messages counts match before and after?

On the read message counts:
- Is there a mix of read and unread messages BEFORE export and you would like to compare those counts?
- The b3 beta resets all flags marking them all unread. I think you are asking to have exported messages retain if they they have been read or not, is this correct?

I did the fast thing to get you full message import. I am in the process of making this smart to not reset the read flag and just leave it as is. This will take a bit longer.

Hopefully we have made progress.
Christopher

**Comment by HBsTB** [comment] 2023-11-19 18:33
Christopher,
yes indeed we have made progress definitiv.

And...no, before exporting haven't there been unread messages.

The exported folder is so to say my archive.
Using the web.de-archive i cannot build this foldertsructure.

1. Is the full folder structure exporting and importing correctly?
I don't no this. The folder seems to be complete, as we have had in the beginning. The completness of messages was a problem.

2. Do the TOTAL messages counts match before and after?
I don't no this too. I can read the count of the imported messages (7802).
The exported messages have been all in status "read".
I see no chance to find out the counts of the original folder, so I can't compare easily by addition of all folder-counts.

This was my question, to a method, showing me the counts also from readed messages in a Thunderbird-folder.
Otherwise i have to compare umpteen folder manuell.

Do you have a solution for showing the counts ?

good luck und success
Hans

**Comment by HBsTB** [comment] 2023-11-19 19:23
Hi, Christopher.
I have found the menue-item for message- count
![Zwischenablage01](https://github.com/thunderbird/import-export-tools-ng/assets/150695686/bbba0357-65d9-45c4-8871-9fd3434a6d94)
i am sick with influenza and have now a break. Counting tomorrow.

Hans

**Comment by cleidigh** [comment] 2023-11-19 20:33
Hans
Sorry you are sick.
When you are better I have b4 for you. This only resets expunged. It also prevents the responded flag that shows the little purple arrows.
Hope you feel better.
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.2/xpi/beta/import-export-tools-ng-14.0.2-b4-tb.xpi
Christopher

**Comment by HBsTB** [comment] 2023-11-20 10:43
be greeted, Christopher.
My Comparation from Export- and Import-Data ist done.
I have executed this by comparing "only" the message- counts.
It's a full success.
On this basic I can say, that all messages have been ex- and imported.

But 2 downer are there.
1. My "so to say"-archive-folder is named "HBs". This folder contents 8 messages. After importing I can't see this.
The first Subfolder in folder "HBs" is "_abgestorbene_Baeume_Oststr". The import shows this and the follwimg folders complete.

Have I to choose another menue-item ?

2. To Import the data without crossing exiting data i have created a new subfolder named "_A_ImportHB". After Import me was shown 7802 messages in this subfolder. This count machtes with the existing messages.
But after deleting this subfolder, in the thunderbird trash this folder is shown to me with 6774 messages.
Are there may be messages, which have been deleted directly without the "detour" over the trash ?


But all in all the first downer is most important to solute.

thanks a lot
Hans

**Comment by cleidigh** [comment] 2023-11-20 16:44
Hans
The first "downer" is your most important so let's address that first.
Is it correct that everything did the export -import correctly EXCEPT your HBs folder should have 8 messages, but shows 0, the subfolders are all ok, correct?
So the easiest thing is send me the export of HBs so I can inspect.

As far as your second, this is really more of a question on the discrepancy of the number of deleted messages, correct?
On this one I really don't know, however, all of the other issues were related to the fact that somehow you have mboxes with messages marked as deleted, but they stayed in the system somehow, this is still a mystery to me.

Christopher

**Comment by HBsTB** [comment] 2023-11-21 11:48
Christopher, here my answer to the first "downer".
The first "downer" is your most important so let's address that first.
Is it correct that everything did the export -import correctly EXCEPT your HBs folder should have 8 messages, but shows 0, the subfolders are all ok, correct?

Yes, it is like that.

So the easiest thing is send me the export of HBs so I can inspect.

My export produces a folder "HBs.sbd" a one file "HBs" without extension. The file I have send. 
The "HBs.sbd"-properties show me 564 files and 103 folder. When I am going to start the transmission i get the notice, if i really would like to send 564 files by this website. I think i'll try it, even by the risk, that only the files are transfered without the folderstructure. May be the folderstructure is important while importing.

This exercise seems to be unsuccsesfull. 
I get the notice, empty files aren't allowed to transfer. And indeed i find 27 files with size zero in this folder and several subfolder.
I made a copy of "Hbs.sbd" and deleted there these zero-files.
By transfering this folder-copy oncemore the notice appears, zero-files not be transfered. My repeated surching in the hole Hbs-copy-folder shows no zero-files.

Which chance i do have ?

Hans

**Comment by HBsTB** [comment] 2023-11-21 12:04
Here now to the 2. "downer".
"..., all of the other issues were related to the fact that somehow you have mboxes with messages marked as deleted, but they stayed in the system somehow, this is still a mystery to me."

This comes mystery to me.
The deleted Data gave been the imported data.
I was the opinion, this problem is soluted with the import.

My first export "Makler_Engelen" has shown missed messages
You have detected the problem and you have reseted some flaggs so that a new import has shown all messages even those, which have marked deleted, but remained in the system.

But how i said, it's a lower priority.
Thanks for making thoughts.

Hans

**Comment by cleidigh** [comment] 2023-11-21 18:56
Guten morgen (my side) Hans
The Hbs mbox imported fine for me with 8 messages, so I am not sure why we see different results.

I have to be honest I am not completely clear on your comments and issues with the particular sbd subfolders. I thought you had said all your folders and messages were exporting and importing correctly?
Christopher

**Comment by HBsTB** [comment] 2023-11-22 12:04
Hi Christopher.
"The Hbs mbox imported fine for me with 8 messages, so I am not sure why we see different results."
I tried something and have done the import in different ways.
First creating a new folder in TB-structure.
Therein I have imported the file "HBs" and it worked. All messages were complete.
Then i started the import of sbd-folder.
And...Hooray...now my "archive"-structure is imported as the original looks.
So, the order of import is important.

I also have made several checks to open attachments form imported messages. 100% success.

So this part of Export-/Import to mbox is closed at my view.
Now i'll start trying the import to outlook.

Thanks for so much help
Hans

**Comment by cleidigh** [comment] 2023-11-22 14:14
Hans
That's great.
But, I guess we are losing you as a Thunderbird user.
That is too bad. But you could do a review!
Christopher

**Comment by cleidigh** [comment] 2023-11-25 20:08
Hans
Hopefully your process is going well.
A review would be very nice %-)
Christopher

**Comment by HBsTB** [comment] 2023-11-28 12:45
Christopher,
is a review here correct ?
I could'nt find antoher place.
Hans

**Comment by cleidigh** [comment] 2023-11-29 17:08
Hans
Thanks for the nice review !
Good luck.
Christopher

**Closed** 2023-12-02 21:01 UTC
