### ISSUE TITLE
Exporting multiple folders, not all emails exported

### ISSUE THREAD

**Issue by GoHost4U** [thunderbird/import-export-tools-ng#568] opened 2024-05-12 11:18 UTC
Hi,

I am trying to export multiple folders from an IMAP server through TB with the hope of importing them to Gmail.

When I export all folders from the IMAP server it creates all the folders on my PC but when you look in each the number of emails within the folders doesnt match the number of emails reported by TB.

If I do 1 folder at a time this works but I have about 120 folders to move.

Also when importing to Gmail it often reports a timeout and just stops.

TB version 115.9.0 (64-bit)
Windows 11 Home
Tools version:  v14.0.2

Thanks in advance for any help!

**Comment by cleidigh** [comment] 2024-05-12 18:01
@GoHost4U 
Thanks for the post.
The subfolder export exposed some structural issues with the old code that I didn't catch with my test sets. I have done a rewrite already in beta, but I need some more beta feedback. It would be great if you can report back your results. It has a lot of debug output still, but I will remove when I feel it's good.

It was not clear to me what you were experiencing with the import, but let's focus on export first. Here is the beta link.
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b5-tb.xpi

@cleidigh

**Comment by GoHost4U** [comment] 2024-05-13 10:28
Thank you for getting back to me.

I have tested the beta and now when you export (using EML messages and subfolders) I get the first folder export successfully but then stops and does not export the rest of the folders.

**Comment by cleidigh** [comment] 2024-05-13 17:47
@GoHost4U 
Well that is not what we wanted.
I have been doing tons of subfolder exports during testing, all successful. The problem is I only have limited test sets that cannot possibly cover all the permutations out there.

Can you give me more details on exactly what you are exporting and the export format. Also the debug output will help. 
Open the console with Control-Shift-J 
Clear with trashcan.
Do your export 
In console, right click and copy all messages 
paste here

@cleidigh

**Comment by delzero** [comment] 2024-05-14 11:21
ME TOO! 

To add a similar case: Ihave been re-using the plugin since it got upgraded to match TB version... previously I (hope I) had no problems. 

But now the recursive folder contents export is dangerously dropping many emails at random - with no error message or warning. It seems to balk at one message in a folder then gives up trying to do any more and moves on to the next folder.

I had looked for clues in the settings and email filenames e.g. spurious characters, too long etc, but didn't see any logic or obvious pattern to the dropped files. So have to defer my basic user skills to the Gods of code out there in developer land...

For my 2cents there are seemingly two places in settings for truncating subject length etc, maybe dev was creating a workaround to bridge the rules in TB with the file system? I tried to ensure my settings were default in that regard. (I'm on Win10).

This plugin is gold, so I really hope dev finds a fix soon...

Thanks!

**Comment by delzero** [comment] 2024-05-14 11:32
...so I followed the instructions and did some test exports - 

It seems to work fine for single folders - i.e. the recursion is the problem area.
But I did get a console message - 

_tb.ui.interaction.message_display - The key length must be limited to 72 characters._ 

So I leave it to the experts to decide what significance that has(!)

**Comment by delzero** [comment] 2024-05-14 11:37
PS I am using the setting Export all messages in folder > EML message format > Messages & index with subfolders

**Comment by cleidigh** [comment] 2024-05-14 18:01
@GoHost4U 
@delzero
I am working as fast as I can on this. I'm frustrated as my test sets didn't catch this. I unfortunately had very few beta testers and they didn't catch this either.
I have a b6 beta that has a rework which looks good to me, lots of debug, but your tests would be helpful.
@GoHost4U which version is your debug output from?
I will have a b7 today.

@cleidigh

**Comment by GoHost4U** [comment] 2024-05-14 18:44
Hiya

My version is v14.0.3-b5

**Comment by cleidigh** [comment] 2024-05-14 20:05
@GoHost4U 
@delzero
b7 fixes the error in the index. Eml should hopefully be good on subfolders. Still working on plaintext.

https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b7-tb.xpi
@cleidigh

**Comment by GoHost4U** [comment] 2024-05-14 22:28
Testing this using the same as before on the Archive folders and this has worked...I am uploading now to see how that goes and will report back

**Comment by cleidigh** [comment] 2024-05-15 16:47
@GoHost4U 
How did you make out?
Christopher

**Comment by GoHost4U** [comment] 2024-05-15 17:08
It's still uploading after a successful download.

Over 100 folders and all seem to have copied locally.

Uploading now

I think we're gonna be good.

30k plus emails!

**Comment by cleidigh** [comment] 2024-05-15 18:21
@GoHost4U 
So all export subfolders and import folders good?
Christopher

**Comment by GoHost4U** [comment] 2024-05-15 18:33
So far I can only confirm the export.

I have seen some small discrepancies while importing some folders but cannot identify what or why. Google seems to timeout regularly but the import carries one so I can only assume the discrepancies are where this interrupts the import and the current email is not imported causing the difference.  However,  most seem to work fine...its still running the import !

**Comment by cleidigh** [comment] 2024-05-15 18:46
@GoHost4U 
Ok sounds good so far.
Importing large scale to imap is always server dependent. Even Google times out as you have seen.
Christopher

**Comment by delzero** [comment] 2024-05-19 10:05
> @GoHost4U @delzero b7 fixes the error in the index. Eml should hopefully be good on subfolders. Still working on plaintext.
> 
> https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b7-tb.xpi @cleidigh

Just installed and retried - output file count now matches perfectly with ~8k items exporting to EML format in folders. Success!

Incredibly fast response from dev - thanks so much!

**Comment by cleidigh** [comment] 2024-05-20 16:18
@delzero 
Thanks very much for testing and patience!
Now that I have two confirmations, I think I can do some final stuff and get this out.
Thanks,
Christopher

**Comment by GoHost4U** [comment] 2024-05-20 17:19
Hi Christopher 

I found the export works fine with multiple folders and sub folders.

Importing works fine for most of these but any emails with large attachments causes Google to timeout and these are not being copied over. I'm not too sure what the size is which causes this as some are copying over with attachments and some not.

Maybe a log of those that didn't make it would be good if at all possible as it's had to find out which failed.

The files are being exported so it's probably Googles restriction!

Other than that I think it's great.

**Comment by cleidigh** [comment] 2024-05-26 20:42
@delzero 
@GoHost4U 
Hey guys.
I finally have b12 with cleanup and I fixed the abort export.
Could you do a a couple subfolder test exports to just make sure I didn't mess anything up from b9? I did a fair amount of regression testing so I don't think anything should fail.

https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b12-tb.xpi

Thanks 
Christopher

**Comment by GoHost4U** [comment] 2024-05-28 08:12
Hi Christopher,

having installed that I cannot get it to work. 1sy I tried checking the version in the "Help" menu and that didnt work then tried an export and nothing...no error screen or anything...

1716880703669	addons.xpi	WARN	Checking C:\Program Files\WindowsApps\MozillaThunderbird.MZLA_115.11.0.0_x64__h5892qc0xkpca\VFS\ProgramFiles\MZLA Package Root\distribution\extensions for addons
1716880703672	addons.xpi	WARN	Checking C:\Program Files\WindowsApps\MozillaThunderbird.MZLA_115.11.0.0_x64__h5892qc0xkpca\VFS\ProgramFiles\MZLA Package Root\distribution\extensions\locale-en-GB for addons
1716880703883	addons.xpi	WARN	Checking C:\Program Files\WindowsApps\MozillaThunderbird.MZLA_115.11.0.0_x64__h5892qc0xkpca\VFS\ProgramFiles\MZLA Package Root\distribution\extensions\locale-es-ES for addons
1716880704476	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880704479	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1716880704482	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
IETNG: mboxImportModule.js -v4 importMboxModule-4.js:32:9
IETNG: mboximportExport.js -v4 mboxImportExport-4.js:39:9
1716880803883	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880803899	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880803910	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880803912	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880824667	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880824671	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880824673	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880824676	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880824678	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880837855	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880837859	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880837862	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880837864	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880862763	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880862793	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880862796	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880862799	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
WebExtensions: start WL shutdown  
Date Tue May 28 2024 09:21:07 GMT+0200 (Central European Summer Time)
implementation.js:2056
WebExtensions: IETNG: OpenBackupDialog start messengerOL.js:75
WebExtensions: end of onunload   
Date Tue May 28 2024 09:21:07 GMT+0200 (Central European Summer Time)
messengerOL.js:244
Start backup check
WebExtensions: start chrome unload 
Date Tue May 28 2024 09:21:07 GMT+0200 (Central European Summer Time)
implementation.js:2163
1716880867432	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867435	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867437	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867439	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867441	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867443	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867445	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
1716880867474	addons.webextension.ImportExportToolsNG@cleidigh.kokkini.net	WARN	Loading extension 'ImportExportToolsNG@cleidigh.kokkini.net': Reading manifest: Warning processing version: version must be a version string consisting of at most 4 integers of at most 9 digits without leading zeros, and separated with dots
redeclaration of const rfc822FieldNames importMboxModule-4.js:1

**Comment by cleidigh** [comment] 2024-05-28 17:11
@GoHost4U 
Thanks, it looks like Thunderbird caching issue. Can you restart Thunderbird and try again.
This caching issue is a pain. If correct, you will see The message for mboximportexport.js -5
That is why it's not working.
Christopher

**Comment by GoHost4U** [comment] 2024-05-28 19:13
OK Restarted TB and the menus seem to work

Tried a new export as i have done before...message appears to say starting export and then nothing...

1716923357504	addons.xpi	WARN	Checking C:\Program Files\WindowsApps\MozillaThunderbird.MZLA_115.11.0.0_x64__h5892qc0xkpca\VFS\ProgramFiles\MZLA Package Root\distribution\extensions for addons
1716923357508	addons.xpi	WARN	Checking C:\Program Files\WindowsApps\MozillaThunderbird.MZLA_115.11.0.0_x64__h5892qc0xkpca\VFS\ProgramFiles\MZLA Package Root\distribution\extensions\locale-en-GB for addons
1716923357508	addons.xpi	WARN	Checking C:\Program Files\WindowsApps\MozillaThunderbird.MZLA_115.11.0.0_x64__h5892qc0xkpca\VFS\ProgramFiles\MZLA Package Root\distribution\extensions\locale-es-ES for addons
1716923357934	addons.xpi	WARN	Addon with ID thunderbird-compact-light@mozilla.org already installed, older version will be disabled
1716923357934	addons.xpi	WARN	Addon with ID thunderbird-compact-dark@mozilla.org already installed, older version will be disabled
IETNG: mboxImportModule.js -v4 importMboxModule-4.js:32:9
IETNG: mboximportExport.js -v5 mboxImportExport-5.js:39:9
TypeError: newTopDir is undefined exportTools.js:447:27
TypeError: newTopDir is undefined exportTools.js:447:27

**Comment by cleidigh** [comment] 2024-05-28 19:18
@GoHost4U 
Sorry for this, let me investigate. I almost decided to stick with b9 for this reason, but I thought that would be incomplete.
I really appreciate the help.
Christopher

**Comment by cleidigh** [comment] 2024-05-28 22:01
@GoHost4U 
Ok good news is I reproduced the error on a different profile so I could test the fix.
If you you can test b13 with a reboot, appreciated. I left debug in to verify.

https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b13-tb.xpi

Christopher

**Comment by cleidigh** [comment] 2024-05-30 16:23
@GoHost4U 
Sorry to bug you, just wanted to see if you had a chance to verify my b13 fix.
Thanks 
Christopher

**Comment by GoHost4U** [comment] 2024-05-30 18:26
Sorry Christopher but I'm away for a few days. I'll look next week.Best Regards,Mark N Johnson Tel: 696 40 15 46 Email: ***@***.***
-------- Original message --------From: Christopher Leidigh ***@***.***> Date: 30/05/2024  17:23  (GMT+00:00) To: thunderbird/import-export-tools-ng ***@***.***> Cc: GoHost4U ***@***.***>, Mention ***@***.***> Subject: Re: [thunderbird/import-export-tools-ng] Exporting multiple folders, not all emails exported (Issue #568) 
@GoHost4U
Sorry to bug you, just wanted to see if you had a chance to verify my b13 fix.
Thanks
Christopher

**Comment by GoHost4U** [comment] 2024-05-30 23:17
Oh yes. Porto in Portugal for some tasting Best Regards,Mark N Johnson Tel: 696 40 15 46 Email: ***@***.***
-------- Original message --------From: Christopher Leidigh ***@***.***> Date: 30/05/2024  19:30  (GMT+00:00) To: thunderbird/import-export-tools-ng ***@***.***> Cc: GoHost4U ***@***.***>, Mention ***@***.***> Subject: Re: [thunderbird/import-export-tools-ng] Exporting multiple folders, not all emails exported (Issue #568) 
@GoHost4U
Great, I hope it's for fun!
Christopher

**Comment by cleidigh** [comment] 2024-05-31 16:01
Allright, we will try a dropbox link.
If you can send an email to my test account : 
test1@kokkini.net
I will send a db link
Christopher

**Comment by cleidigh** [comment] 2024-05-31 23:02
@GoHost4U 
Wow, that sounds amazing! Never got to Portugal myself. Please have a glass for me.
BUT, don't drink too much, you have to test Monday  %-}

Cheers and enjoy!!
Christopher

**Comment by GoHost4U** [comment] 2024-06-03 09:49
Hi Christopher

 

I did an export of quite a few as per the screenshot.

 

However, due to the size of some of the attachments they did not upload to Gmail.

 

This is where a report might help but at the end of the day it does seem to be working as far as that’s concerned.

 

 

Best Regards,

Mark N Johnson

 

Description: Description: email_sig

 

Any prices that are quoted are subject to IVA at the prevailing rate.

Our standard terms and conditions apply. These can be viewed on our website.

Errors and ommissions accepted.

 

This e-mail is confidential and should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage mechanism.

All personal information contained in this message is protected by the Spanish law (Ley 15/1999, de 13 de Diciembre, de protección de datos de carácter personal), and it is no allowed to use or communicate to anyone out of legal regulations

**Comment by cleidigh** [comment] 2024-06-03 15:52
@GoHost4U 
Thank you sir!
So the exports went ok, i think I can release now.
I'm trying to understand your comments about moving to Gmail, this is a totally separate operation, yes?
Moving folders from a local folder to Gmail imap?
I've seen poor performance of Gmail uploads. Unfortunately, if this is what you are referring to, it's out of my hands. That would be a Thunderbird action and I don't know how good they are about reporting.

If it's something to do with ImportExportTools, let me know.
Hope your trip was fun!
Christopher

**Comment by GoHost4U** [comment] 2024-06-03 17:23
Hi Christopher,

 

I am sorry I didn’t explain that well; too much port!

 

---->I'm trying to understand your comments about moving to Gmail, this is a totally separate operation, yes?
Moving folders from a local folder to Gmail imap?

 

When I say “move” I meant import using your add-on. This all works except for the emails with large attachments. I’ve only tried importing to Gmail and I know there are issues with timeouts when trying to import to Gmail. So when I tried importing what I had exported some emails did not make it to Gmail. I notice there’s a small delay then a message from TB saying there’s a timeout and then it carries on. Most import correctly but I think the ones that don’t are the ones with the large attachments. As there are so many I list of those that don’t make it would be useful but this is a wish list rather than a necessity. I also feel that with a normal IMAP email server the larger emails will import so this only reflects on Gmail.

 

I am currently importing these emails to a standard server to see how that gets on. I will revert back once its done.

 

Trip was excellent by the way, thank you.

 

Best Regards,

Mark N Johnson

 

Description: Description: email_sig

 

Any prices that are quoted are subject to IVA at the prevailing rate.

Our standard terms and conditions apply. These can be viewed on our website.

Errors and ommissions accepted.

 

This e-mail is confidential and should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage mechanism.

All personal information contained in this message is protected by the Spanish law (Ley 15/1999, de 13 de Diciembre, de protección de datos de carácter personal), and it is no allowed to use or communicate to anyone out of legal regulations

**Comment by cleidigh** [comment] 2024-06-03 17:44
ha ha, that's the best excuse ever!
So the Gmail issue is Thunderbird move?
What was the best thing you ate and drank?
Christopher

**Comment by GoHost4U** [comment] 2024-06-04 09:13
Hi Christopher,

 

The best port I drank was a Dalva White port of 40 years (160€ a bottle!) and the best food was some tapas type food. However, all the food there was good and quite reasonable.

 

As for the import:

 

I imported the emails which I had previously exported (as per the screenshot) and this time they ALL imported correctly. This included the large emails with the big attachments so this proves that the previous import issues were down to Google’s restrictions or “failings”.

 

 

Best Regards,

Mark N Johnson

 

Description: Description: email_sig

 

Any prices that are quoted are subject to IVA at the prevailing rate.

Our standard terms and conditions apply. These can be viewed on our website.

Errors and ommissions accepted.

 

This e-mail is confidential and should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage mechanism.

All personal information contained in this message is protected by the Spanish law (Ley 15/1999, de 13 de Diciembre, de protección de datos de carácter personal), and it is no allowed to use or communicate to anyone out of legal regulations

**Comment by cleidigh** [comment] 2024-06-05 16:17
@GoHost4U 
40 year old port and tapas sounds great!

Good thing on your Gmail import, thanks for all of your testing, will probably release v14.0.3 into the Q today.
Not sure what your plans are for Thunderbird 128, but I already have pretty stable beta:
https://github.com/thunderbird/import-export-tools-ng/issues/575

I will stop bugging you now
Salud
Christopher

**Comment by GoHost4U** [comment] 2024-06-06 10:47
Hi Christopher

 

No problem.

 

 

Best Regards,

Mark N Johnson

 

Description: Description: email_sig

 

Any prices that are quoted are subject to IVA at the prevailing rate.

Our standard terms and conditions apply. These can be viewed on our website.

Errors and ommissions accepted.

 

This e-mail is confidential and should not be used by anyone who is not the original intended recipient. If you have received this e-mail in error please inform the sender and delete it from your mailbox or any other storage mechanism.

All personal information contained in this message is protected by the Spanish law (Ley 15/1999, de 13 de Diciembre, de protección de datos de carácter personal), and it is no allowed to use or communicate to anyone out of legal regulations

**Closed** 2024-06-24 15:43 UTC
