### ISSUE TITLE
Backup dialog -  __MSG_ locale strings not substituted on shutdown dialog

### ISSUE THREAD

**Issue by lntech24** [thunderbird/import-export-tools-ng#559] opened 2024-04-18 15:44 UTC
When I close Thunderbird to backup, the message "msg dialog title" appears. what to do?

![PHOTO-2024-04-17-13-19-49](https://github.com/thunderbird/import-export-tools-ng/assets/167452903/808f1319-32b4-4b32-b6d8-1894006d2f44)

**Comment by cleidigh** [comment] 2024-04-18 17:52
@lntech24 
Thanks for the post, sorry for the issue.
Do you have backups enabled?
Also, there is a strings issue, what locale are you using?
@cleidigh

**Comment by cleidigh** [comment] 2024-04-18 22:00
@lntech24 
It looks like you are on Windows using the Italian standard locale?
I just double checked and the Italian dialog looks ok.
Can you capture the log on closing?
@cleidigh

**Comment by lntech24** [comment] 2024-04-19 05:35
I have two client PCs with Windows 11 with the same functions enabled. one PC has the problem, one doesn't. I have backups enabled in both. I tried in English and the problem is there

**Comment by JGonzJGonz** [comment] 2024-04-19 09:36
Hi,
had a very similar problem, with locale = German.
Setting locale => English US solved the problem.
Have fun!

**Comment by lntech24** [comment] 2024-04-19 10:52
how do you change the language?

**Comment by JGonzJGonz** [comment] 2024-04-19 11:06
Hi,
in Thunderbird: Menu Tools, Settings.
Scroll down to Language & Appearance, then Language.
If English US isn't installed, get it via 'Search for more languages'.
Have fun!

**Comment by lntech24** [comment] 2024-04-19 13:42
does this change also the change thunderbird language?

**Comment by JGonzJGonz** [comment] 2024-04-19 13:47
Hi,
yep, it changes the interface language. In my case some dialogs keep the previous language, partially ...
But the backUp works again :)
Have fun!

**Comment by cleidigh** [comment] 2024-04-19 16:32
All
I cannot reproduce this in the various locales. There is something preventing the strings update for localization from occurring. 

If someone can capture the debug output when shutting down where the problem occurs, maybe we'll get some clue.

Thanks 
@cleidigh

**Comment by cleidigh** [comment] 2024-04-19 16:50
@JGonzJGonz 
I'm particularly interested in your report that changing to en locale makes the problem go away. If there was an issue of missing de localization strings this would make sense, however, all strings are there and the dialog in de works for me.

Could you capture your debug output?
Set locale to de
open and clear the debug console 
exit Thunderbird, backup dialog should appear with untranslated strings.
Copy and post debug output here.
Thanks 
Christopher

**Comment by JGonzJGonz** [comment] 2024-04-19 17:26
@cleidigh 
Hi,
tried as you asked for, but now it works ...

Only, when starting a backUp (that will work), I get this:
> tb.ui.interaction.toolbox - The key length must be limited to 72 characters.

Dunno if this related, but after a startUp in any locale I get:
> IETNG: mboxImportModule.js -v4 importMboxModule-4.js:32:9
> IETNG: mboximportExport.js -v4 mboxImportExport-4.js:39:9

After startUp in german locale I get additionally:
> TypeError: console is not a function messengerOL.js:178:11

Hope this helps. Let me know if I should try something else! :)

**Comment by JGonzJGonz** [comment] 2024-04-19 17:27
Ooops, forgot:
options dialog works as intended.

Have fun!

**Comment by cleidigh** [comment] 2024-04-19 17:32
@JGonzJGonz 
Thanks for your quick response!
So you now see the correct dialog in the de locale?
The problem just went away?
Maybe the code had to marinate?? %-}
@cleidigh

**Comment by JGonzJGonz** [comment] 2024-04-19 18:02
Hi,
correct dialog in English as well as in German, right.

My initial error dialog at the start of backUp was different - but I don't remember it anymore :/
Will capture it next time & post here. Had the same some months ago already, guess a TB update fixed it then.

Yes, just changing the locale did it for me - and now it works in both locales. Maybe a string somewhere got corrupted & needed correction?

Anyways, have fun!

**Comment by cleidigh** [comment] 2024-04-19 18:30
@JGonzJGonz 
Very odd!
Well please let me know if anything happens. I can't think how it would resolve on its own
Maybe someone's log will help.
Thanks for your understanding (and have fun!)

@cleidigh

**Comment by 107EMA** [comment] 2024-04-21 21:41
I am getting the same pop up msg dialog title when I close since 17/4/2024. I have altered locale and language to english us as mentioned above and this has made no difference. Could you please advice what to try next. Thanks

**Comment by cleidigh** [comment] 2024-04-21 22:40
@107EMA 
@Intech24
As I have mentioned above, with many test in different locales, I can't reproduce this. There is some edge condition preventing the dialog string substitution. Perhaps a system timing issue.
Two things to try.
First, if you do a manual backup from the ietng button, what does that dialog do?
Second can you capture the debug output on shutdown?
I'm hoping there is a clue.
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-22 06:05
Hi ive got the same probleme on a lot of computer.

First thanks for your plug in.

Second there are two screen capture, one with manual backup, which work s well, and the second when closing thunderbird.

![NG](https://github.com/thunderbird/import-export-tools-ng/assets/114312059/7cce2ddd-1b14-46ee-8856-882a6900ac0a)
![NG1](https://github.com/thunderbird/import-export-tools-ng/assets/114312059/9d449930-f92f-4a6f-af2a-40665a843989)

Thanks

**Comment by cleidigh** [comment] 2024-04-22 21:10
@mrdmswit 
Thanks for your post and support!
Your first screenshot is one data point that supports my assumption that this is a shutdown timing problem.
The dialogs are the same with one manually run and the same run on shutdown.

The strings for the current locale are substituted on dialog opening. 
I think there is something system dependent preventing substitution. I just can't reproduce on my system.

Can you capture the Debug console output on shutdown and post?
I may also need to post a debug beta to track down.
Thanks
@cleidigh

**Comment by 107EMA** [comment] 2024-04-22 21:47
This is what I get on automatic backup 

![image](https://github.com/thunderbird/import-export-tools-ng/assets/132673001/18db0fec-f867-42aa-ade4-26eea94ff82b)
The backup has to be cancelled as it just sits there not doing anything no matter how long its left running.
Manual back up works ok

**Comment by cleidigh** [comment] 2024-04-22 21:50
@107EMA 
Thanks, any chance you could capture and post the debug console output on shutdown?
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-23 05:32
@cleidigh 
Hi ,
Yes i can, just tell me how  to do capture the debug console because i don t know?

**Comment by cleidigh** [comment] 2024-04-23 17:52
@107EMA 
Apologies, should not assume.
To open the debug console use Control-Shift-J
Then use the trash icon to clear
For capturing the output of interest:

- Before Thunderbird shutdown, make sure the console is open and clear
- Shutdown and the dialog without localization should appear 
- Don't do anything with the dialog 
- Switch to the debug console 
- Use Right click and Copy all messages 
- Paste here

I am working on a test version. Check here if I post before you try, in the case I get it up we will use that
Christopher

**Comment by mrdmswit** [comment] 2024-04-23 18:13
@cleidigh 
![NG](https://github.com/thunderbird/import-export-tools-ng/assets/114312059/d1927f8e-e4d0-4410-b9b9-69544b49d994)

**Comment by cleidigh** [comment] 2024-04-23 18:20
@mrdmswit 
Thanks, that is what I needed.
Unfortunately, nada, no errors!
I am perplexed.
So I am rushing to post a debug beta because there has to be a shutdown timing issue.
How much longer will you be online?
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-23 18:24
@cleidigh 
one hour.

**Comment by cleidigh** [comment] 2024-04-23 18:31
@mrdmswit 
Ok, I cannot get it out that quick.
One thing I just realized is that your debug didn't even show:
"Start backup check"
Which is done before shutdown and opening the backup dialog 
Not sure why we don't...
I will add more debug.
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-23 18:36
@cleidigh 
ok if you need any other information don't hesitate to ask me

**Comment by cleidigh** [comment] 2024-04-23 18:48
@mrdmswit 
Thanks.
I will leave instructions for the beta.
@cleidigh

**Comment by 107EMA** [comment] 2024-04-23 19:19
I get the same screen 
![image](https://github.com/thunderbird/import-export-tools-ng/assets/132673001/c09f437c-ad23-41e5-85c1-888c01a713de)

**Comment by cleidigh** [comment] 2024-04-23 19:26
@107EMA 
There is an issue with the Thunderbird debug console where all messages don't appear which is happening here. I just tried another method, try this : 

Open and clear debug
Then go to the Add-ons tab and disable IETNG, then check the debug, show debug that way.
@cleidigh

**Comment by 107EMA** [comment] 2024-04-23 19:33
![image](https://github.com/thunderbird/import-export-tools-ng/assets/132673001/b23de3ca-168b-4db8-8438-bd6db575a5b7)

**Comment by cleidigh** [comment] 2024-04-23 19:40
@107EMA 
Wow, nothing???
Did the dialog come up?
Christopher

**Comment by 107EMA** [comment] 2024-04-23 19:42
Yes, it came up when I disabled IETNG

**Comment by 107EMA** [comment] 2024-04-23 19:47
I don't know if I am doing this right but this time I got 
![image](https://github.com/thunderbird/import-export-tools-ng/assets/132673001/64a15a80-f10c-4804-8f38-eafcd7b8801a)
![image](https://github.com/thunderbird/import-export-tools-ng/assets/132673001/261495ea-9a88-4b88-b3d5-641137bc6053)

**Comment by cleidigh** [comment] 2024-04-23 19:52
Great, those messages are probably showing us that the scripts are not being run!
I will add some more debug and post.
How long will you be online?
@cleidigh

**Comment by 107EMA** [comment] 2024-04-23 19:56
I am around until 10.30 ish

**Comment by cleidigh** [comment] 2024-04-23 19:58
ok, hopefully I can have something, but those messages are throwing me for a loop.
May take a deeper investigation.
Christopher

**Comment by cleidigh** [comment] 2024-04-23 20:48
@107EMA 
Could you downgrade to 14.0.1?
There were simultaneously changing Thunderbird, I want to see if that still works.
The fact that I can't reproduce is crazy and making this fix very difficult!
@cleidigh

**Comment by 107EMA** [comment] 2024-04-23 20:53
I can downgrade to 14.0.1 but I can't see where to do that

**Comment by cleidigh** [comment] 2024-04-23 20:58
Go here 
https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/versions/

Download v14.0.1
From gear icon in addons tab, install from file, pick where you downloaded.
@cleidigh

**Comment by 107EMA** [comment] 2024-04-23 21:05
Thank you, back ups are now working correctly again with no errors or empty files. :)

**Comment by cleidigh** [comment] 2024-04-23 21:11
Good, so no idea what is going on considering I only changed the translation api to the new method, but from your screenshot we are not running any scripts for the dialog.
I'll stop bugging you until I have something to test.
Thanks!
@cleidigh

**Comment by cleidigh** [comment] 2024-04-23 22:01
@107EMA 
Any chance you are online?
I have a debug beta that loads the scripts differently.
@cleidigh

**Comment by cleidigh** [comment] 2024-04-23 22:38
All
We found one clue in the debug output thanks to  @107EMA .
The issue is quite low level and very odd.
None of the scripts are being loaded for the dialog. It makes no sense.
I have a beta that loads them differently that may work on your systems.

Download the beta here: 
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b1-tb.xpi

Go to addons tab, click gear, install addon from file
choose v14.0.3-b1 download.

If you get a corrupted message, follow below instructions.
https://github.com/cleidigh/printing-tools-ng/issues/154

Now open the debug console with Control-Shift-J 
Back to Thunderbird 
From addons tab, disable IETNG 
If dialog is good, we have a fix
If not, go to debug console and right click, copy all messages or do screenshot.
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-24 16:49
@cleidigh 
Hi
Still get the same issue with beta version.

**Comment by cleidigh** [comment] 2024-04-24 16:57
@107EMA 
@mrdmswit 
Thanks guys, sorry my fix didn't work.
We have our developer call tomorrow and hopefully can get some ideas.
@cleidigh

**Comment by cleidigh** [comment] 2024-04-24 22:22
All
Until I get this resolved you can do backup manually or downgrade to v14.0.1 per below : 

> Go here https://addons.thunderbird.net/en-US/thunderbird/addon/importexporttools-ng/versions/
> 
> Download v14.0.1 From gear icon in addons tab, install from file, pick where you downloaded. @cleidigh

**Comment by cleidigh** [comment] 2024-04-25 22:53
@mrdmswit 
@lntech24 
@107EMA 
@JGonzJGonz 
I have reproduced the error, I am hoping in the same way you have.
Check the backup options, what is the setting for : 
 Use a "modal" window 

If I uncheck this I get the error, if I use modal, it works.
If you can check and report, great.

In our developer call we agreed it was a shutdown race condition. We could not come up with a reason v14.0.1 behaves differently.

This has some timing debug
https://github.com/thunderbird/import-export-tools-ng/blob/v14.0.3/xpi/beta/import-export-tools-ng-14.0.3-b2-tb.xpi

Set to modal dialog and open console
Disable in addons tab
capture debug

Reenable, change to non modal 
repeat above and post.

Thanks 
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-26 07:29
@cleidigh 
Hi 
Yes when using modal windows no issue, but nothing for in error consol with modal windows or not.

**Comment by cleidigh** [comment] 2024-04-26 16:35
@mrdmswit 
So Using the modal option fixed the issue?
The debug only shows if you use disable, even then sometimes it doesn't show.
I think I need to remove the option because it doesn't work in the new architecture.
I don't know why v14.0.1 would work differently, might be a timing difference.
It will be interesting to get others results.
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-26 16:44
@cleidigh 
Yes using modal fixed the issue, test on 12 computers. Disable or enable ive got nothing in error console...
@mrdmswit

**Comment by cleidigh** [comment] 2024-04-26 16:48
@mrdmswit 
Very good!
I just went back and checked v14.0.1 with non modal and that fails in a similar fashion. 
Thanks for your help and patience on this!
@cleidigh

**Comment by mrdmswit** [comment] 2024-04-26 16:51
@cleidigh 
your plug-in is very useful to us, it's the least we can do to help you
@mrdmswit

**Comment by cleidigh** [comment] 2024-04-26 16:56
Thanks @mrdmswit 
It's a pleasure to work and help appreciative people, especially those who understand that its hard to not have issues with software when there are so many variables!
@cleidigh

**Comment by cleidigh** [comment] 2024-04-29 19:51
@107EMA 
@lntech24 
Can you guys check if you have the modal window off on the backup options?
I think that is the issue, I can reproduce. 
The non modal option is not compatible with the current architecture and will be removed.
@cleidigh

**Comment by lntech24** [comment] 2024-04-30 05:41
I have a PC with modal mode active and everything works correctly (Windows 11). in the morning I check if the PC where I'm having problems has the function active and if so, deactivate it. Thank you

**Comment by JGonzJGonz** [comment] 2024-04-30 08:19
Hi,
very busy these days & on the road a lot, sorry.
Just read about the 'modal' option & decided to try - v14.0.2 with TB 115.10.1 (32-Bit):

First, checking: 'Modal' is OFF, backUp is due. Closing TB. Getting the dreaded dialog from OP. Console:
> Diese Seite befindet sich im Kompatibilitätsmodus (Quirks). Das Seitenlayout kann beeinflusst werden. Verwenden Sie für den Standardmodus "<!DOCTYPE html>". background.html
> IETNG: mboxImportModule.js -v4 importMboxModule-4.js:32:9
> IETNG: mboximportExport.js -v4 mboxImportExport-4.js:39:9
> TypeError: console is not a function messengerOL.js:178:11
> tb.ui.interaction.toolbox - The key length must be limited to 72 characters.

'Cancel'. Restarting TB, setting 'Modal' to ON. Closing TB. BackUp runs as desired! Console is the same as above, but the 'tb.ui.interaction.toolbox' line is missing now.

Very strange!

**Comment by 107EMA** [comment] 2024-04-30 09:16
Hi Sorry I've been unavailable to check new setting until today, I have just tried it and setting Modal to on stops the error message and everything backs up as expected. Thankyou.

**Comment by cleidigh** [comment] 2024-04-30 18:29
@mrdmswit 
@107EMA 
@JGonzJGonz 
@lntech24 
Thank you all for confirming. I will remove this option since only modal is appropriate for the current Thunderbird architecture.
I have other stuff to do, but this will be in v14.0.3.
Thanks for working through this together.
@cleidigh

**Closed** 2024-06-24 15:49 UTC
Labels: bug
